<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE menu-definition [
<!ELEMENT menuItem EMPTY>
<!ATTLIST menuItem 
	id ID #REQUIRED
	name CDATA #REQUIRED
	pattern CDATA ""
	url CDATA ""
	urlConcatVar CDATA ""
	target CDATA ""
	roles CDATA ""
	i18nKey CDATA "">
<!ELEMENT menu (menuItem)+>
<!ATTLIST menu 
	name CDATA #REQUIRED
	i18nKey CDATA #REQUIRED
	pattern CDATA ""
	roles CDATA #REQUIRED>
<!ELEMENT menu-definition (menu)+>
]>
<menu-definition>
  <menu name="cabecera" i18nKey="menu.cabecera." roles="ROLE_ADMINISTRADOR,ROLE_PUBLICADOR,ROLE_CATALOGADOR,ROLE_DOCENTE,ROLE_INACTIVO">
    <menuItem id="portada" name="portada" pattern="acercaDeAgrega,accesibilidad,visualizadorcontenidos/es/pode/visualizador/presentacion/faqs,mapa,visualizadorcontenidos/es/pode/visualizador/presentacion/contacto,visualizadorcontenidos/es/pode/visualizador/presentacion/portada,modificarPerfil,visualizadorcontenidos/es/pode/visualizador/presentacion/noticias,visualizadorcontenidos/es/pode/visualizador/presentacion/informes,visualizadorcontenidos/es/pode/visualizador/presentacion/descargas,listarAgregaTags,listarMisTags,modificarTag,mostrarOdesAgregaTags,mostrarOdesMisTags" url="url_portada"/>
    <menuItem id="arbol" name="arbolCabecera" pattern="arbolCurricular,areaCurricularBusqueda,tipoBusquedaArbol,seleccionTipoBusqueda,navegarTesauro" url="url_seleccionTipoBusqueda" roles="ROLE_ADMINISTRADOR,ROLE_PUBLICADOR,ROLE_CATALOGADOR,ROLE_DOCENTE,ROLE_ANONYMOUS" />
    <menuItem id="objetos" name="objetosPersonales" pattern="objetosPersonales,objetosPropuestos,objetosPublicados,objetosCompartidos,objetosPublicadosAutonomos" url="url_gestorFlujo" roles="ROLE_DOCENTE"/>
    <menuItem id="comunidad" name="comunidad" pattern="visualizadorcontenidos/es/pode/visualizador/presentacion/gestionContactosUsuario,gestionFavoritos,gestionGrupoPublico,gestionGruposAsociados,gestionGruposPublicos,gestionUsuarioPublico" url="url_micomunidad" roles="ROLE_ADMINISTRADOR,ROLE_PUBLICADOR,ROLE_CATALOGADOR,ROLE_DOCENTE"/>
    <menuItem id="admin" name="admin" pattern="portaladministracion,objetosDespublicados,objetosPendientes,objetosPublicosAutonomos,ModificadorWeb,adminTag" url="url_portada_admin" roles="ROLE_ADMINISTRADOR,ROLE_PUBLICADOR,ROLE_CATALOGADOR"/>
  </menu>
  <menu name="lateral_generico" i18nKey="menu.lateral.generico." pattern="visualizadorcontenidos,TaggingWeb" roles="ROLE_ADMINISTRADOR,ROLE_PUBLICADOR,ROLE_CATALOGADOR,ROLE_DOCENTE,ROLE_ANONYMOUS,ROLE_INACTIVO">
    <menuItem id="noticias" name="noticias" pattern="noticias/" url="url_noticias"/>
    <menuItem id="informes" name="informes" pattern="informes" url="url_informes_portada"/>
    <menuItem id="descargas" name="descargas" pattern="descargas" url="url_descargas_portal"/>
    <menuItem id="utilidades" name="utilidades" pattern="utilidades,agregaSlider,agregaContenidoDinamico" url="url_utilidades"/>
    <menuItem id="tagging" name="tagging" pattern="TaggingWeb" url="url_taggingWeb"/>
    <menuItem id="estadisticas" name="estadisticas" pattern="estadisticas" url="url_estadisticas"/>
  </menu>
  <menu name="lateral_admin" i18nKey="menu.lateral.administrador." pattern="portaladministracion,gestorFlujo,ModificadorWeb,adminTag" roles="ROLE_ADMINISTRADOR,ROLE_CATALOGADOR,ROLE_PUBLICADOR">
    <menuItem id="admin_noticias" name="noticias" pattern="noticias" url="url_noticias_admin" i18nKey="menu.lateral.generico." roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_faqs" name="FAQs" pattern="faqs" url="url_faqs_admin" i18nKey="menu.lateral.generico." roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_descargas" name="descargas" pattern="descargas" url="url_admin_descargas" i18nKey="menu.lateral.generico." roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_configuracion" name="configuracion" pattern="Configuracion" url="url_configuracion" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_estructurasEdu" name="estructurasEdu" pattern="estructuraseducativas" url="url_estructurasEdu" roles="ROLE_ADMINISTRADOR"/>
	<menuItem id="admin_configuracion_plataforma" name="configuracionPlataforma" pattern="ConfiguracionPlataforma" url="url_configuracion_plataforma" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_usuarios" name="usuarios" pattern="Usuario" url="url_adminusuarios_usuarios" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_estadisticas" name="estadisticas" pattern="Estadisticas" url="url_adminestadisticas_estadisticas" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_roles" name="roles" pattern="Grupo" url="url_adminusuarios_grupos" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_catalogadores" name="catalogadores" pattern="catalogadores" url="url_catalogadores" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_itinerarios" name="itinerariosAprendizaje" pattern="itinerariosAprendizaje" url="url_itinerarios" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_tagging" name="tagging" pattern="adminTag/" url="url_admin_taggingWeb" i18nKey="menu.lateral.generico." roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_planificador" name="planificador" pattern="planificador" url="url_planificador" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_informes" name="informes" pattern="Informe" url="url_informes" i18nKey="menu.lateral.generico." roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_carga" name="cargaMasiva" pattern="gestionCarga" url="url_cargaMasiva" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_modificador" name="modificador" pattern="ModificadorWeb" url="url_modificador" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_nodo" name="nodo" pattern="Nodo" url="url_nodos_admin" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_repositorios" name="repositoriosExternos" pattern="RepositoriosExternos" url="url_repositorios_admin" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_logs" name="logs" pattern="logs" url="url_logs" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_monitorizador" name="monitorizador" pattern="monitorizar" url="url_monitorizar" roles="ROLE_ADMINISTRADOR"/>
    <menuItem id="admin_catalogador" name="catalogador" pattern="objetosPendientesCatalogacion" url="url_gestorFlujo_catalogacion" roles="ROLE_CATALOGADOR"/>
    <menuItem id="admin_publicador" name="publicador" pattern="objetosDespublicados,objetosPendientes/" url="url_gestorFlujo_admin" roles="ROLE_PUBLICADOR"/>
  	<menuItem id="admin_publicosAutonomos" name="publicosAutonomos" pattern="objetosPublicosAutonomos/" url="url_gestorFlujo_autonomos" roles="ROLE_ADMINISTRADOR"/>
  	<menuItem id="admin_coninapropiados" name="contenidosInapropiados" pattern="contenidoInapropiado,ContenidoInapropiado/" url="url_contenidoinapropiado" roles="ROLE_ADMINISTRADOR,ROLE_PUBLICADOR"/>
  </menu>
  <menu name="metanavegacion" i18nKey="metanavegacion." roles="ROLE_ANONYMOUS,ROLE_ADMINISTRADOR,ROLE_PUBLICADOR,ROLE_CATALOGADOR,ROLE_DOCENTE,ROLE_INACTIVO">
    <menuItem id="salir" name="salir" url="url_salir" roles="ROLE_ADMINISTRADOR,ROLE_PUBLICADOR,ROLE_CATALOGADOR,ROLE_DOCENTE,ROLE_INACTIVO"/>
    <menuItem id="perfil" name="perfil" url="url_perfil" roles="ROLE_ADMINISTRADOR,ROLE_PUBLICADOR,ROLE_CATALOGADOR,ROLE_DOCENTE"/>
    <menuItem id="ayuda" name="ayuda" url="url_ayuda2" urlConcatVar="HELP_URL" target="blank" roles="ROLE_ANONYMOUS,ROLE_ADMINISTRADOR,ROLE_PUBLICADOR,ROLE_CATALOGADOR,ROLE_DOCENTE,ROLE_INACTIVO"/>
    <menuItem id="restringida" name="restringida" url="url_restringida" roles="ROLE_ANONYMOUS"/>
  </menu>
  
</menu-definition>
